FROM mcr.microsoft.com/playwright:v1.58.2-jammy
WORKDIR /app
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

RUN apt-get update && apt-get install -y \
    --no-install-recommends \
    openssl \
    curl \
    && rm -rf /var/lib/apt/lists/*
